config/routes.rb
HackerNewsRails::Application.routes.draw do

  root :to => 'posts#index'

  resources :users
  match '/signup' => 'users#new'

  get    '/login'  => 'sessions#new'
  post   '/login'  => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :posts do
    resources :vote
  end

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes
  attr_accessible :title, :link_url

  def self.by_votes
     joins('left join votes on votes.post_id = posts.id').
     select('posts.*, sum(votes.value) as vote_total').
     group('posts.id').
     order('vote_total DESC')
  end

  def add_or_update_vote(value, current_user)
    votes.where(user_id: current_user.id).first_or_create(value: value)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessor :password_confirmation

  attr_accessible :name, :email, :password, :password_confirmation

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, presence: true
  validates_confirmation_of :password
  
  has_secure_password

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :value

  validates_uniqueness_of :post_id, scope: :user_id
  validates_inclusion_of :value, in: [1, -1]
  #validate :ensure_not_author


  def ensure_not_author
    errors.add :user_id, "is the creator of this post" if post.user_id = user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    user = User.find(session[:user])
    post = Post.new(params[:post])
    user.posts << post
    if post.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # ...
  end

  def create
    if User.authenticate(params[:user][:name], params[:user][:password])
      @user = User.find_by_name(params[:user][:name])
      session[:user] = @user.id
      redirect_to root_path
    else
      @errors = {error: "Invalid name or password."}
      erb :login
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    p params[:user]
    @user = User.new(params[:user])
    if @user.save
      session[:user] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors
      puts @user.errors.keys
      redirect_to new_user_path
    end
  end

end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  
  def new
    @post = Post.find(params[:post_id])
    @post.add_or_update_vote(1, current_user)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

def current_user
  @user ||= User.find(session[:user])
end

app/views/layouts/_header_partial.html.erb
<header>
  <%= image_tag("https://news.ycombinator.com/y18.gif") %>
  <%= link_to "Handsom News", :root, {:class => "logo"} %>
  <nav class="content">
    <ul>
      <li><a href="/posts/new">submit</li>
    </ul>
  </nav>
  <nav class="user">
    <ul>
      <% unless session[:user] %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% else %>
        <li><%= link_to "Logout", logout_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header_partial" %>

<%= yield %>

</body>
</html>

app/views/posts/index.erb
<div class="container">
  <table class="list_all_posts">
  <% @posts.each_with_index do |post, index| %>
    <tr>
      <td class="index_col"><%= index + 1 %></td>
      <td class="upvote_col"><%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), new_post_vote_path(post) %></td>
      <td><%= link_to post.title, post.link_url %><span class="url_view">(<%= post.link_url %>)</span><br>
      <span class="posts_second_line_info"><%= post.votes.count %> votes | <%= link_to "comments (#{post.comments.count})", post_path(post) %></span></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/posts/new.erb
<div class='container'>
  <%= form_for @post do |p| %>
    <%= p.text_field :title,  :placeholder => "Title" %>
    <%= p.text_field :link_url, :placeholder => "url" %>
    <%= p.submit "Submit" %>
  <% end %>
</div>

app/views/users/index.erb
test user index

app/views/users/new.erb
<div class="container">
  <div class="container_padding">
    <h1>Sign Up!</h1>
    <% if @errors %>
      <%= erb :_errors, locals: {errors: @errors} %>
    <% end %>

    <div id="signup">

      <%= form_for @user do |f|  %>
        <%=     f.text_field     :name, placeholder: "Username" %>
        <%=     f.email_field    :email, placeholder: "Email" %>
        <%=     f.password_field :password, placeholder: "Password" %>
        <%=     f.password_field :password_confirmation, placeholder: "Confirm password" %>
        <%=     f.submit "Sign up!" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/show.erb
<div class="container">
  
  <% if current_user == @user %>
    <%= form_for @user do |f|  %>
      <%=     f.text_field     :name, placeholder: "Username" %>
      <%=     f.email_field    :email, placeholder: "Email" %>
      <%=     f.password_field :password, placeholder: "Password" %>
      <%=     f.password_field :password_confirmation, placeholder: "Confirm password" %>
      <%=     f.submit "Sign up!" %>
    <% end %>
  <% end %>

  <% unless current_user == @user %>
    <ul>
      <li>User: <%= @user.name %></li>
      <li>Created: <%= @user.created_at %></li>
      <li>Email: <%= @user.email %></li>
    </ul>
  <% end %>

  <a href="/posts/users/<%= current_user.id %>">submissions</a>
  <a href="/comments/users/<%= current_user.id %>">comments</a>

</div>